# Generated by Django 4.1.4 on 2023-01-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name1',
            new_name='name',
        ),
    ]
